# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(first_name: "abc", last_name: "abc", email: "abc@abc.com", phone_number: "9739202135")
User.create(first_name: "def", last_name: "def", email: "def@def.com", phone_number: "9739202136")
User.create(first_name: "ghi", last_name: "ghi", email: "ghi@ghi.com", phone_number: "9739202134")
User.create(first_name: "jkl", last_name: "jkl", email: "jkl@jkl.com", phone_number: "9739202133")
User.create(first_name: "mno", last_name: "mno", email: "mno@mno.com", phone_number: "9739202131")
User.create(first_name: "pqr", last_name: "pqr", email: "pqr@pqr.com", phone_number: "9739202132")
User.create(first_name: "stu", last_name: "stu", email: "stu@stu.com", phone_number: "9739202130")
User.create(first_name: "vwx", last_name: "vwx", email: "vwx@vwx.com", phone_number: "9739202138")
User.create(first_name: "YZ", last_name: "YZ", email: "YZ@YZ.com", phone_number: "9739202139")

Follower.create(name: "abc abc", phone_number: "9739202121", follower_id: 3, following_id: 2)
Follower.create(name: "abc abc", phone_number: "9739202131", follower_id: 4, following_id: 2)
Follower.create(name: "abc abc", phone_number: "9739202141", follower_id: 5, following_id: 2)
Follower.create(name: "abc abc", phone_number: "9739202151", follower_id: 1, following_id: 3)
Follower.create(name: "abc abc", phone_number: "9739202161", follower_id: 5, following_id: 3)
Follower.create(name: "abc abc", phone_number: "9739202171", follower_id: 8, following_id: 3)
Follower.create(name: "abc abc", phone_number: "9739202181", follower_id: 1, following_id: 4)
Follower.create(name: "abc abc", phone_number: "9739202122", follower_id: 10, following_id: 4)
Follower.create(name: "abc abc", phone_number: "9739202133", follower_id: 9, following_id: 4)
Follower.create(name: "abc abc", phone_number: "9739202144", follower_id: 8, following_id: 5)
Follower.create(name: "abc abc", phone_number: "9739202155", follower_id: 9, following_id: 5)
Follower.create(name: "abc abc", phone_number: "9739202166", follower_id: 7, following_id: 5)
Follower.create(name: "abc abc", phone_number: "9739202177", follower_id: 3, following_id: 6)
Follower.create(name: "abc abc", phone_number: "9739202121", follower_id: 3, following_id: 6)
Follower.create(name: "abc abc", phone_number: "9739202131", follower_id: 4, following_id: 6)
Follower.create(name: "abc abc", phone_number: "9739202141", follower_id: 5, following_id: 6)
Follower.create(name: "abc abc", phone_number: "9739202151", follower_id: 1, following_id: 7)
Follower.create(name: "abc abc", phone_number: "9739202161", follower_id: 5, following_id: 7)
Follower.create(name: "abc abc", phone_number: "9739202171", follower_id: 8, following_id: 7)
Follower.create(name: "abc abc", phone_number: "9739202181", follower_id: 1, following_id: 8)
Follower.create(name: "abc abc", phone_number: "9739202122", follower_id: 10, following_id: 8)
Follower.create(name: "abc abc", phone_number: "9739202121", follower_id: 9, following_id: 9)
Follower.create(name: "abc abc", phone_number: "9739202131", follower_id: 2, following_id: 9)
Follower.create(name: "abc abc", phone_number: "9739202141", follower_id: 3, following_id: 9)
Follower.create(name: "abc abc", phone_number: "9739202151", follower_id: 4, following_id: 9)
Follower.create(name: "abc abc", phone_number: "9739202161", follower_id: 2, following_id: 10)
Follower.create(name: "abc abc", phone_number: "9739202171", follower_id: 8, following_id: 10)
Follower.create(name: "abc abc", phone_number: "9739202181", follower_id: 9, following_id: 10)
Follower.create(name: "abc abc", phone_number: "9739202122", follower_id: 1, following_id: 10)
Follower.create(name: "abc abc", phone_number: "9739202161", follower_id: 2, following_id: 10)
Follower.create(name: "abc abc", phone_number: "9739202171", follower_id: 4, following_id: 1)
Follower.create(name: "abc abc", phone_number: "9739202181", follower_id: 3, following_id: 1)
Follower.create(name: "abc abc", phone_number: "9739202122", follower_id: 2, following_id: 1)

Post.create(title: "php", post_content: "php is old language but gold", user_id: 2)
Post.create(title: "mysql", post_content: "good sql database", user_id: 3)
Post.create(title: "fsfk", post_content: "", user_id: 4)
Post.create(title: "sfsf", post_content: "php is old language but gold", user_id: 5)
Post.create(title: "fssfsf", post_content: "php is old language but gold", user_id: 6)
Post.create(title: "sfsfsf", post_content: "php is old language but gold", user_id: 7)
Post.create(title: "fsfsf", post_content: "php is old language but gold", user_id: 8)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 9)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 10)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 1)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 2)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 3)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 4)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 5)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 6)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 7)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 8)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 9)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 10)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 1)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 2)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 3)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 4)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 5)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 6)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 7)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 8)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 9)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 10)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 1)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 2)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 3)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 4)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 5)
Post.create(title: "php", post_content: "php is old language but gold", user_id: 6)
